photo_front:
    resource: "@COMMANDEPHOTOFrontBundle/Resources/config/routing.yml"
    prefix:   /

photo_admin:
    resource: "@COMMANDEPHOTOAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
